package com.xueda.food.auth.dao;

import com.xueda.food.auth.model.AuthUsers;
import java.util.List;

public interface AuthUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_users
     *
     * @mbg.generated
     */
    int insert(AuthUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_users
     *
     * @mbg.generated
     */
    AuthUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_users
     *
     * @mbg.generated
     */
    List<AuthUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthUsers record);
}